# fly.toml file generated for rtv on 2023-02-13T17:25:01-08:00

app = "rtv"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []


[env]

[experimental]
  auto_rollback = true

[mounts]
source="mtv_queue"
destination="/src/queue"
